"""
Page 1: Word selection and memorization.
"""
from models import VocabularyManager

TITLE = "หมวดคำศัพท์"

def build(query=None):
    """Build context dict for page 1."""
    if query is None:
        query = {}

    sample_data = [
        {"word": "security", "length": 8, "difficulty": "medium", "category": "Daily Life", "hint_th": "ความปลอดภัย", "times_used": 0, "is_picked": "no"},
        {"word": "routine", "length": 7, "difficulty": "medium", "category": "Daily Life", "hint_th": "กิจวัตร", "times_used": 0, "is_picked": "no"},
        {"word": "appointment", "length": 11, "difficulty": "medium", "category": "Daily Life", "hint_th": "นัดหมาย", "times_used": 0, "is_picked": "no"},
        {"word": "convenient", "length": 10, "difficulty": "medium", "category": "Daily Life", "hint_th": "สะดวก", "times_used": 0, "is_picked": "no"},
        {"word": "schedule", "length": 8, "difficulty": "medium", "category": "Daily Life", "hint_th": "ตารางเวลา / กำหนดการ", "times_used": 0, "is_picked": "no"},
        {"word": "frequently", "length": 10, "difficulty": "medium", "category": "Daily Life", "hint_th": "บ่อยครั้ง", "times_used": 0, "is_picked": "no"},
        {"word": "occasionally", "length": 11, "difficulty": "medium", "category": "Daily Life", "hint_th": "เป็นครั้งคราว", "times_used": 0, "is_picked": "no"},
        {"word": "prepare", "length": 7, "difficulty": "medium", "category": "Daily Life", "hint_th": "เตรียม", "times_used": 0, "is_picked": "no"},
        {"word": "organize", "length": 8, "difficulty": "medium", "category": "Daily Life", "hint_th": "จัดระเบียบ", "times_used": 0, "is_picked": "no"},
        {"word": "manage", "length": 6, "difficulty": "medium", "category": "Daily Life", "hint_th": "จัดการ", "times_used": 0, "is_picked": "no"},
        {"word": "avoid", "length": 5, "difficulty": "medium", "category": "Daily Life", "hint_th": "หลีกเลี่ยง", "times_used": 0, "is_picked": "no"},
        {"word": "maintain", "length": 8, "difficulty": "medium", "category": "Daily Life", "hint_th": "รักษา / คงไว้", "times_used": 0, "is_picked": "no"},
        {"word": "require", "length": 7, "difficulty": "medium", "category": "Daily Life", "hint_th": "ต้องการ / จำเป็นต้อง", "times_used": 0, "is_picked": "no"},
        {"word": "prefer", "length": 6, "difficulty": "medium", "category": "Daily Life", "hint_th": "ชอบมากกว่า", "times_used": 0, "is_picked": "no"},
        {"word": "available", "length": 9, "difficulty": "medium", "category": "Daily Life", "hint_th": "มีอยู่ / พร้อมใช้งาน", "times_used": 0, "is_picked": "no"},
        {"word": "responsible", "length": 11, "difficulty": "medium", "category": "Daily Life", "hint_th": "รับผิดชอบ", "times_used": 0, "is_picked": "no"},
        {"word": "necessary", "length": 9, "difficulty": "medium", "category": "Daily Life", "hint_th": "จำเป็น", "times_used": 0, "is_picked": "no"},
        {"word": "immediately", "length": 11, "difficulty": "medium", "category": "Daily Life", "hint_th": "ทันที", "times_used": 0, "is_picked": "no"},
        {"word": "ordinary", "length": 8, "difficulty": "medium", "category": "Daily Life", "hint_th": "ธรรมดา / ทั่วไป", "times_used": 0, "is_picked": "no"},
        {"word": "improve", "length": 7, "difficulty": "medium", "category": "Daily Life", "hint_th": "ปรับปรุง / พัฒนา", "times_used": 0, "is_picked": "no"},

        {"word": "relationship", "length": 12, "difficulty": "medium", "category": "People & Relationships", "hint_th": "ความสัมพันธ์", "times_used": 0, "is_picked": "no"},
        {"word": "neighbor", "length": 8, "difficulty": "medium", "category": "People & Relationships", "hint_th": "เพื่อนบ้าน", "times_used": 0, "is_picked": "no"},
        {"word": "colleague", "length": 9, "difficulty": "medium", "category": "People & Relationships", "hint_th": "เพื่อนร่วมงาน", "times_used": 0, "is_picked": "no"},
        {"word": "relative", "length": 8, "difficulty": "medium", "category": "People & Relationships", "hint_th": "ญาติ", "times_used": 0, "is_picked": "no"},
        {"word": "supportive", "length": 10, "difficulty": "medium", "category": "People & Relationships", "hint_th": "ให้การสนับสนุน", "times_used": 0, "is_picked": "no"},
        {"word": "respectful", "length": 10, "difficulty": "medium", "category": "People & Relationships", "hint_th": "ให้ความเคารพ", "times_used": 0, "is_picked": "no"},
        {"word": "friendly", "length": 8, "difficulty": "medium", "category": "People & Relationships", "hint_th": "เป็นมิตร", "times_used": 0, "is_picked": "no"},
        {"word": "confident", "length": 9, "difficulty": "medium", "category": "People & Relationships", "hint_th": "มั่นใจ", "times_used": 0, "is_picked": "no"},
        {"word": "honest", "length": 6, "difficulty": "medium", "category": "People & Relationships", "hint_th": "ซื่อสัตย์", "times_used": 0, "is_picked": "no"},
        {"word": "patient", "length": 7, "difficulty": "medium", "category": "People & Relationships", "hint_th": "อดทน", "times_used": 0, "is_picked": "no"},
        {"word": "polite", "length": 6, "difficulty": "medium", "category": "People & Relationships", "hint_th": "สุภาพ", "times_used": 0, "is_picked": "no"},
        {"word": "communicate", "length": 11, "difficulty": "medium", "category": "People & Relationships", "hint_th": "สื่อสาร", "times_used": 0, "is_picked": "no"},
        {"word": "discuss", "length": 7, "difficulty": "medium", "category": "People & Relationships", "hint_th": "พูดคุย / อภิปราย", "times_used": 0, "is_picked": "no"},
        {"word": "advice", "length": 6, "difficulty": "medium", "category": "People & Relationships", "hint_th": "คำแนะนำ", "times_used": 0, "is_picked": "no"},
        {"word": "trust", "length": 5, "difficulty": "medium", "category": "People & Relationships", "hint_th": "ความไว้วางใจ", "times_used": 0, "is_picked": "no"},
        {"word": "similar", "length": 7, "difficulty": "medium", "category": "People & Relationships", "hint_th": "คล้ายกัน", "times_used": 0, "is_picked": "no"},
        {"word": "different", "length": 9, "difficulty": "medium", "category": "People & Relationships", "hint_th": "แตกต่าง", "times_used": 0, "is_picked": "no"},
        {"word": "experience", "length": 10, "difficulty": "medium", "category": "People & Relationships", "hint_th": "ประสบการณ์", "times_used": 0, "is_picked": "no"},
        {"word": "behavior", "length": 8, "difficulty": "medium", "category": "People & Relationships", "hint_th": "พฤติกรรม", "times_used": 0, "is_picked": "no"},
        {"word": "personality", "length": 11, "difficulty": "medium", "category": "People & Relationships", "hint_th": "บุคลิกภาพ", "times_used": 0, "is_picked": "no"},

        {"word": "assignment", "length": 10, "difficulty": "medium", "category": "Education", "hint_th": "งานที่ได้รับมอบหมาย", "times_used": 0, "is_picked": "no"},
        {"word": "lecture", "length": 7, "difficulty": "medium", "category": "Education", "hint_th": "การบรรยาย", "times_used": 0, "is_picked": "no"},
        {"word": "semester", "length": 8, "difficulty": "medium", "category": "Education", "hint_th": "ภาคการศึกษา", "times_used": 0, "is_picked": "no"},
        {"word": "subject", "length": 7, "difficulty": "medium", "category": "Education", "hint_th": "วิชา", "times_used": 0, "is_picked": "no"},
        {"word": "academic", "length": 8, "difficulty": "medium", "category": "Education", "hint_th": "ด้านการศึกษา", "times_used": 0, "is_picked": "no"},
        {"word": "research", "length": 8, "difficulty": "medium", "category": "Education", "hint_th": "การวิจัย", "times_used": 0, "is_picked": "no"},
        {"word": "knowledge", "length": 9, "difficulty": "medium", "category": "Education", "hint_th": "ความรู้", "times_used": 0, "is_picked": "no"},
        {"word": "practice", "length": 8, "difficulty": "medium", "category": "Education", "hint_th": "การฝึกฝน", "times_used": 0, "is_picked": "no"},
        {"word": "exam", "length": 4, "difficulty": "medium", "category": "Education", "hint_th": "การสอบ", "times_used": 0, "is_picked": "no"},
        {"word": "grade", "length": 5, "difficulty": "medium", "category": "Education", "hint_th": "คะแนน / เกรด", "times_used": 0, "is_picked": "no"},
        {"word": "project", "length": 7, "difficulty": "medium", "category": "Education", "hint_th": "โครงงาน", "times_used": 0, "is_picked": "no"},
        {"word": "presentation", "length": 12, "difficulty": "medium", "category": "Education", "hint_th": "การนำเสนอ", "times_used": 0, "is_picked": "no"},
        {"word": "deadline", "length": 8, "difficulty": "medium", "category": "Education", "hint_th": "กำหนดส่ง", "times_used": 0, "is_picked": "no"},
        {"word": "concentrate", "length": 11, "difficulty": "medium", "category": "Education", "hint_th": "มีสมาธิ", "times_used": 0, "is_picked": "no"},
        {"word": "memorize", "length": 8, "difficulty": "medium", "category": "Education", "hint_th": "ท่องจำ", "times_used": 0, "is_picked": "no"},
        {"word": "understand", "length": 10, "difficulty": "medium", "category": "Education", "hint_th": "เข้าใจ", "times_used": 0, "is_picked": "no"},
        {"word": "review", "length": 6, "difficulty": "medium", "category": "Education", "hint_th": "ทบทวน", "times_used": 0, "is_picked": "no"},
        {"word": "explain", "length": 7, "difficulty": "medium", "category": "Education", "hint_th": "อธิบาย", "times_used": 0, "is_picked": "no"},
        {"word": "improve", "length": 7, "difficulty": "medium", "category": "Education", "hint_th": "พัฒนา", "times_used": 0, "is_picked": "no"},
        {"word": "skill", "length": 5, "difficulty": "medium", "category": "Education", "hint_th": "ทักษะ", "times_used": 0, "is_picked": "no"},

        {"word": "career", "length": 6, "difficulty": "medium", "category": "Work & Career", "hint_th": "อาชีพ / เส้นทางอาชีพ", "times_used": 0, "is_picked": "no"},
        {"word": "employee", "length": 8, "difficulty": "medium", "category": "Work & Career", "hint_th": "พนักงาน", "times_used": 0, "is_picked": "no"},
        {"word": "employer", "length": 8, "difficulty": "medium", "category": "Work & Career", "hint_th": "นายจ้าง", "times_used": 0, "is_picked": "no"},
        {"word": "position", "length": 8, "difficulty": "medium", "category": "Work & Career", "hint_th": "ตำแหน่งงาน", "times_used": 0, "is_picked": "no"},
        {"word": "interview", "length": 9, "difficulty": "medium", "category": "Work & Career", "hint_th": "การสัมภาษณ์", "times_used": 0, "is_picked": "no"},
        {"word": "salary", "length": 6, "difficulty": "medium", "category": "Work & Career", "hint_th": "เงินเดือน", "times_used": 0, "is_picked": "no"},
        {"word": "experience", "length": 10, "difficulty": "medium", "category": "Work & Career", "hint_th": "ประสบการณ์", "times_used": 0, "is_picked": "no"},
        {"word": "responsibility", "length": 14, "difficulty": "medium", "category": "Work & Career", "hint_th": "ความรับผิดชอบ", "times_used": 0, "is_picked": "no"},
        {"word": "meeting", "length": 7, "difficulty": "medium", "category": "Work & Career", "hint_th": "การประชุม", "times_used": 0, "is_picked": "no"},
        {"word": "project", "length": 7, "difficulty": "medium", "category": "Work & Career", "hint_th": "โครงการ", "times_used": 0, "is_picked": "no"},
        {"word": "deadline", "length": 8, "difficulty": "medium", "category": "Work & Career", "hint_th": "กำหนดส่ง", "times_used": 0, "is_picked": "no"},
        {"word": "professional", "length": 12, "difficulty": "medium", "category": "Work & Career", "hint_th": "เป็นมืออาชีพ", "times_used": 0, "is_picked": "no"},
        {"word": "manager", "length": 7, "difficulty": "medium", "category": "Work & Career", "hint_th": "ผู้จัดการ", "times_used": 0, "is_picked": "no"},
        {"word": "department", "length": 10, "difficulty": "medium", "category": "Work & Career", "hint_th": "แผนก", "times_used": 0, "is_picked": "no"},
        {"word": "schedule", "length": 8, "difficulty": "medium", "category": "Work & Career", "hint_th": "ตารางงาน", "times_used": 0, "is_picked": "no"},
        {"word": "training", "length": 8, "difficulty": "medium", "category": "Work & Career", "hint_th": "การฝึกอบรม", "times_used": 0, "is_picked": "no"},
        {"word": "task", "length": 4, "difficulty": "medium", "category": "Work & Career", "hint_th": "งาน / หน้าที่", "times_used": 0, "is_picked": "no"},
        {"word": "career", "length": 6, "difficulty": "medium", "category": "Work & Career", "hint_th": "อาชีพ", "times_used": 0, "is_picked": "no"},
        {"word": "promote", "length": 7, "difficulty": "medium", "category": "Work & Career", "hint_th": "เลื่อนตำแหน่ง", "times_used": 0, "is_picked": "no"},
        {"word": "achieve", "length": 7, "difficulty": "medium", "category": "Work & Career", "hint_th": "บรรลุ / ทำสำเร็จ", "times_used": 0, "is_picked": "no"},

        {"word": "ingredient", "length": 10, "difficulty": "medium", "category": "Food & Dining", "hint_th": "ส่วนผสม", "times_used": 0, "is_picked": "no"},
        {"word": "restaurant", "length": 10, "difficulty": "medium", "category": "Food & Dining", "hint_th": "ร้านอาหาร", "times_used": 0, "is_picked": "no"},
        {"word": "menu", "length": 4, "difficulty": "medium", "category": "Food & Dining", "hint_th": "เมนูอาหาร", "times_used": 0, "is_picked": "no"},
        {"word": "order", "length": 5, "difficulty": "medium", "category": "Food & Dining", "hint_th": "สั่งอาหาร", "times_used": 0, "is_picked": "no"},
        {"word": "delicious", "length": 9, "difficulty": "medium", "category": "Food & Dining", "hint_th": "อร่อย", "times_used": 0, "is_picked": "no"},
        {"word": "flavor", "length": 6, "difficulty": "medium", "category": "Food & Dining", "hint_th": "รสชาติ", "times_used": 0, "is_picked": "no"},
        {"word": "portion", "length": 7, "difficulty": "medium", "category": "Food & Dining", "hint_th": "ปริมาณ / ส่วน", "times_used": 0, "is_picked": "no"},
        {"word": "healthy", "length": 7, "difficulty": "medium", "category": "Food & Dining", "hint_th": "มีสุขภาพดี", "times_used": 0, "is_picked": "no"},
        {"word": "vegetable", "length": 9, "difficulty": "medium", "category": "Food & Dining", "hint_th": "ผัก", "times_used": 0, "is_picked": "no"},
        {"word": "beverage", "length": 8, "difficulty": "medium", "category": "Food & Dining", "hint_th": "เครื่องดื่ม", "times_used": 0, "is_picked": "no"},
        {"word": "dessert", "length": 7, "difficulty": "medium", "category": "Food & Dining", "hint_th": "ของหวาน", "times_used": 0, "is_picked": "no"},
        {"word": "recommend", "length": 9, "difficulty": "medium", "category": "Food & Dining", "hint_th": "แนะนำ", "times_used": 0, "is_picked": "no"},
        {"word": "taste", "length": 5, "difficulty": "medium", "category": "Food & Dining", "hint_th": "รสชาติ / ลิ้มรส", "times_used": 0, "is_picked": "no"},
        {"word": "fresh", "length": 5, "difficulty": "medium", "category": "Food & Dining", "hint_th": "สดใหม่", "times_used": 0, "is_picked": "no"},
        {"word": "spicy", "length": 5, "difficulty": "medium", "category": "Food & Dining", "hint_th": "เผ็ด", "times_used": 0, "is_picked": "no"},
        {"word": "sweet", "length": 5, "difficulty": "medium", "category": "Food & Dining", "hint_th": "หวาน", "times_used": 0, "is_picked": "no"},
        {"word": "bitter", "length": 6, "difficulty": "medium", "category": "Food & Dining", "hint_th": "ขม", "times_used": 0, "is_picked": "no"},
        {"word": "receipt", "length": 7, "difficulty": "medium", "category": "Food & Dining", "hint_th": "ใบเสร็จ", "times_used": 0, "is_picked": "no"},
        {"word": "cuisine", "length": 7, "difficulty": "medium", "category": "Food & Dining", "hint_th": "อาหาร / รูปแบบอาหาร", "times_used": 0, "is_picked": "no"},
        {"word": "diet", "length": 4, "difficulty": "medium", "category": "Food & Dining", "hint_th": "การควบคุมอาหาร", "times_used": 0, "is_picked": "no"},

        {"word": "journey", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "การเดินทาง", "times_used": 0, "is_picked": "no"},
        {"word": "destination", "length": 11, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "จุดหมายปลายทาง", "times_used": 0, "is_picked": "no"},
        {"word": "transportation", "length": 14, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "การขนส่ง / การเดินทาง", "times_used": 0, "is_picked": "no"},
        {"word": "departure", "length": 9, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "การออกเดินทาง", "times_used": 0, "is_picked": "no"},
        {"word": "arrival", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "การมาถึง", "times_used": 0, "is_picked": "no"},
        {"word": "ticket", "length": 6, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "ตั๋ว", "times_used": 0, "is_picked": "no"},
        {"word": "station", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "สถานี", "times_used": 0, "is_picked": "no"},
        {"word": "traffic", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "การจราจร", "times_used": 0, "is_picked": "no"},
        {"word": "vehicle", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "ยานพาหนะ", "times_used": 0, "is_picked": "no"},
        {"word": "direction", "length": 9, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "ทิศทาง", "times_used": 0, "is_picked": "no"},
        {"word": "route", "length": 5, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "เส้นทาง", "times_used": 0, "is_picked": "no"},
        {"word": "luggage", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "สัมภาระ", "times_used": 0, "is_picked": "no"},
        {"word": "passport", "length": 8, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "หนังสือเดินทาง", "times_used": 0, "is_picked": "no"},
        {"word": "booking", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "การจอง", "times_used": 0, "is_picked": "no"},
        {"word": "hotel", "length": 5, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "โรงแรม", "times_used": 0, "is_picked": "no"},
        {"word": "explore", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "สำรวจ", "times_used": 0, "is_picked": "no"},
        {"word": "local", "length": 5, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "ท้องถิ่น", "times_used": 0, "is_picked": "no"},
        {"word": "abroad", "length": 6, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "ต่างประเทศ", "times_used": 0, "is_picked": "no"},
        {"word": "delay", "length": 5, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "ความล่าช้า", "times_used": 0, "is_picked": "no"},
        {"word": "convenient", "length": 10, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "สะดวก", "times_used": 0, "is_picked": "no"},

        {"word": "exercise", "length": 8, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "การออกกำลังกาย", "times_used": 0, "is_picked": "no"},
        {"word": "healthy", "length": 7, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "มีสุขภาพดี", "times_used": 0, "is_picked": "no"},
        {"word": "lifestyle", "length": 9, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "รูปแบบการใช้ชีวิต", "times_used": 0, "is_picked": "no"},
        {"word": "nutrition", "length": 9, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "โภชนาการ", "times_used": 0, "is_picked": "no"},
        {"word": "habit", "length": 5, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "นิสัย / กิจวัตร", "times_used": 0, "is_picked": "no"},
        {"word": "sleep", "length": 5, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "การนอนหลับ", "times_used": 0, "is_picked": "no"},
        {"word": "stress", "length": 6, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ความเครียด", "times_used": 0, "is_picked": "no"},
        {"word": "relax", "length": 5, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ผ่อนคลาย", "times_used": 0, "is_picked": "no"},
        {"word": "energy", "length": 6, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "พลังงาน", "times_used": 0, "is_picked": "no"},
        {"word": "balance", "length": 7, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "สมดุล", "times_used": 0, "is_picked": "no"},
        {"word": "prevent", "length": 7, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ป้องกัน", "times_used": 0, "is_picked": "no"},
        {"word": "recover", "length": 7, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ฟื้นตัว", "times_used": 0, "is_picked": "no"},
        {"word": "condition", "length": 9, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "สภาพ / ภาวะ", "times_used": 0, "is_picked": "no"},
        {"word": "regular", "length": 7, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "สม่ำเสมอ", "times_used": 0, "is_picked": "no"},
        {"word": "physical", "length": 8, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ทางกายภาพ", "times_used": 0, "is_picked": "no"},
        {"word": "mental", "length": 6, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ทางจิตใจ", "times_used": 0, "is_picked": "no"},
        {"word": "medical", "length": 7, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ทางการแพทย์", "times_used": 0, "is_picked": "no"},
        {"word": "symptom", "length": 7, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "อาการ", "times_used": 0, "is_picked": "no"},
        {"word": "treatment", "length": 9, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "การรักษา", "times_used": 0, "is_picked": "no"},
        {"word": "immunity", "length": 8, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ภูมิคุ้มกัน", "times_used": 0, "is_picked": "no"},

        {"word": "technology", "length": 10, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "เทคโนโลยี", "times_used": 0, "is_picked": "no"},
        {"word": "device", "length": 6, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "อุปกรณ์", "times_used": 0, "is_picked": "no"},
        {"word": "application", "length": 11, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "แอปพลิเคชัน", "times_used": 0, "is_picked": "no"},
        {"word": "software", "length": 8, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ซอฟต์แวร์", "times_used": 0, "is_picked": "no"},
        {"word": "hardware", "length": 8, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ฮาร์ดแวร์", "times_used": 0, "is_picked": "no"},
        {"word": "network", "length": 7, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "เครือข่าย", "times_used": 0, "is_picked": "no"},
        {"word": "account", "length": 7, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "บัญชีผู้ใช้", "times_used": 0, "is_picked": "no"},
        {"word": "password", "length": 8, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "รหัสผ่าน", "times_used": 0, "is_picked": "no"},
        {"word": "privacy", "length": 7, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ความเป็นส่วนตัว", "times_used": 0, "is_picked": "no"},
        {"word": "security", "length": 8, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ความปลอดภัย", "times_used": 0, "is_picked": "no"},
        {"word": "message", "length": 7, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ข้อความ", "times_used": 0, "is_picked": "no"},
        {"word": "communication", "length": 13, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "การสื่อสาร", "times_used": 0, "is_picked": "no"},
        {"word": "download", "length": 8, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ดาวน์โหลด", "times_used": 0, "is_picked": "no"},
        {"word": "upload", "length": 6, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "อัปโหลด", "times_used": 0, "is_picked": "no"},
        {"word": "connect", "length": 7, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "เชื่อมต่อ", "times_used": 0, "is_picked": "no"},
        {"word": "digital", "length": 7, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ดิจิทัล", "times_used": 0, "is_picked": "no"},
        {"word": "online", "length": 6, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ออนไลน์", "times_used": 0, "is_picked": "no"},
        {"word": "update", "length": 6, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "อัปเดต", "times_used": 0, "is_picked": "no"},
        {"word": "search", "length": 6, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ค้นหา", "times_used": 0, "is_picked": "no"},
        {"word": "website", "length": 7, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "เว็บไซต์", "times_used": 0, "is_picked": "no"},

        {"word": "purchase", "length": 8, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "การซื้อ", "times_used": 0, "is_picked": "no"},
        {"word": "customer", "length": 8, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ลูกค้า", "times_used": 0, "is_picked": "no"},
        {"word": "price", "length": 5, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ราคา", "times_used": 0, "is_picked": "no"},
        {"word": "discount", "length": 8, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ส่วนลด", "times_used": 0, "is_picked": "no"},
        {"word": "budget", "length": 6, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "งบประมาณ", "times_used": 0, "is_picked": "no"},
        {"word": "payment", "length": 7, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "การชำระเงิน", "times_used": 0, "is_picked": "no"},
        {"word": "cash", "length": 4, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "เงินสด", "times_used": 0, "is_picked": "no"},
        {"word": "receipt", "length": 7, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ใบเสร็จ", "times_used": 0, "is_picked": "no"},
        {"word": "expensive", "length": 9, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ราคาแพง", "times_used": 0, "is_picked": "no"},
        {"word": "affordable", "length": 10, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ราคาไม่แพง", "times_used": 0, "is_picked": "no"},
        {"word": "expensive", "length": 9, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "แพง", "times_used": 0, "is_picked": "no"},
        {"word": "save", "length": 4, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ประหยัด / ออม", "times_used": 0, "is_picked": "no"},
        {"word": "spend", "length": 5, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ใช้จ่าย", "times_used": 0, "is_picked": "no"},
        {"word": "income", "length": 6, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "รายได้", "times_used": 0, "is_picked": "no"},
        {"word": "expense", "length": 7, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ค่าใช้จ่าย", "times_used": 0, "is_picked": "no"},
        {"word": "wallet", "length": 6, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "กระเป๋าสตางค์", "times_used": 0, "is_picked": "no"},
        {"word": "change", "length": 6, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "เงินทอน / เปลี่ยน", "times_used": 0, "is_picked": "no"},
        {"word": "quality", "length": 7, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "คุณภาพ", "times_used": 0, "is_picked": "no"},
        {"word": "brand", "length": 5, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ยี่ห้อ", "times_used": 0, "is_picked": "no"},
        {"word": "refund", "length": 6, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "การคืนเงิน", "times_used": 0, "is_picked": "no"},

        {"word": "environment", "length": 11, "difficulty": "medium", "category": "Environment & Society", "hint_th": "สิ่งแวดล้อม", "times_used": 0, "is_picked": "no"},
        {"word": "pollution", "length": 9, "difficulty": "medium", "category": "Environment & Society", "hint_th": "มลพิษ", "times_used": 0, "is_picked": "no"},
        {"word": "recycle", "length": 7, "difficulty": "medium", "category": "Environment & Society", "hint_th": "รีไซเคิล", "times_used": 0, "is_picked": "no"},
        {"word": "waste", "length": 5, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ขยะ / ของเสีย", "times_used": 0, "is_picked": "no"},
        {"word": "community", "length": 9, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ชุมชน", "times_used": 0, "is_picked": "no"},
        {"word": "society", "length": 7, "difficulty": "medium", "category": "Environment & Society", "hint_th": "สังคม", "times_used": 0, "is_picked": "no"},
        {"word": "public", "length": 6, "difficulty": "medium", "category": "Environment & Society", "hint_th": "สาธารณะ", "times_used": 0, "is_picked": "no"},
        {"word": "resource", "length": 8, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ทรัพยากร", "times_used": 0, "is_picked": "no"},
        {"word": "energy", "length": 6, "difficulty": "medium", "category": "Environment & Society", "hint_th": "พลังงาน", "times_used": 0, "is_picked": "no"},
        {"word": "climate", "length": 7, "difficulty": "medium", "category": "Environment & Society", "hint_th": "สภาพภูมิอากาศ", "times_used": 0, "is_picked": "no"},
        {"word": "natural", "length": 7, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ตามธรรมชาติ", "times_used": 0, "is_picked": "no"},
        {"word": "protect", "length": 7, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ปกป้อง", "times_used": 0, "is_picked": "no"},
        {"word": "reduce", "length": 6, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ลด", "times_used": 0, "is_picked": "no"},
        {"word": "increase", "length": 8, "difficulty": "medium", "category": "Environment & Society", "hint_th": "เพิ่มขึ้น", "times_used": 0, "is_picked": "no"},
        {"word": "community", "length": 9, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ชุมชน", "times_used": 0, "is_picked": "no"},
        {"word": "volunteer", "length": 9, "difficulty": "medium", "category": "Environment & Society", "hint_th": "อาสาสมัคร", "times_used": 0, "is_picked": "no"},
        {"word": "responsibility", "length": 14, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ความรับผิดชอบ", "times_used": 0, "is_picked": "no"},
        {"word": "social", "length": 6, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ทางสังคม", "times_used": 0, "is_picked": "no"},
        {"word": "local", "length": 5, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ท้องถิ่น", "times_used": 0, "is_picked": "no"},
        {"word": "future", "length": 6, "difficulty": "medium", "category": "Environment & Society", "hint_th": "อนาคต", "times_used": 0, "is_picked": "no"}
    ]

    manager = VocabularyManager(sample_data)
    medium_items = manager.filter_by_difficulty("medium")

    categories = []
    category_names = [
        "Daily Life (ชีวิตประจำวัน)",
        "People & Relationships (ผู้คนและความสัมพันธ์)",
        "Education (การศึกษา)",
        "Work & Career (งานและอาชีพ)",
        "Food & Dining (อาหารและการรับประทานอาหาร)",
        "Travel & Transportation (การเดินทางและพาหนะ)",
        "Health & Lifestyle (สุขภาพและการใช้ชีวิต)",
        "Technology & Communication (เทคโนโลยีและการสื่อสาร)",
        "Shopping & Money (การซื้อของและการเงิน)",
        "Environment & Society (สิ่งแวดล้อมและสังคม)"
    ]

    for category_name in category_names:
        category_words = []

        for item in medium_items:
            if item.get("category") == category_name.split(" (")[0]:
                category_words.append(
                    f"{item.get('word')} = {item.get('hint_th')}"
                )

        categories.append({
            "name": category_name,
            "words": category_words
        })

    return {
        "description": "หมวดคำศัพท์ทั้งหมด",
        "categories": categories
    }