"""
Page 1: Word selection and memorization.
"""
from models import VocabularyManager

TITLE = "หมวดคำศัพท์"

def build(query=None):
    """Build context dict for page 1."""
    if query is None:
        query = {}

    sample_data = [
        {"word": "security", "length": 8, "difficulty": "medium", "category": "Daily Life", "hint_th": "ความปลอดภัย", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "routine", "length": 7, "difficulty": "medium", "category": "Daily Life", "hint_th": "กิจวัตร", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "appointment", "length": 11, "difficulty": "medium", "category": "Daily Life", "hint_th": "นัดหมาย", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "convenient", "length": 10, "difficulty": "medium", "category": "Daily Life", "hint_th": "สะดวก", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "schedule", "length": 8, "difficulty": "medium", "category": "Daily Life", "hint_th": "ตารางเวลา / กำหนดการ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "frequent", "length": 10, "difficulty": "medium", "category": "Daily Life", "hint_th": "บ่อย", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "occasional", "length": 11, "difficulty": "medium", "category": "Daily Life", "hint_th": "เป็นครั้งคราว", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "prepare", "length": 7, "difficulty": "medium", "category": "Daily Life", "hint_th": "เตรียม", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "organize", "length": 8, "difficulty": "medium", "category": "Daily Life", "hint_th": "จัดระเบียบ", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "manage", "length": 6, "difficulty": "medium", "category": "Daily Life", "hint_th": "จัดการ", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "avoid", "length": 5, "difficulty": "medium", "category": "Daily Life", "hint_th": "หลีกเลี่ยง", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "maintain", "length": 8, "difficulty": "medium", "category": "Daily Life", "hint_th": "รักษา / คงไว้", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "require", "length": 7, "difficulty": "medium", "category": "Daily Life", "hint_th": "ต้องการ / จำเป็นต้อง", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "prefer", "length": 6, "difficulty": "medium", "category": "Daily Life", "hint_th": "ชอบมากกว่า", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "available", "length": 9, "difficulty": "medium", "category": "Daily Life", "hint_th": "มีอยู่ / พร้อมใช้งาน", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "responsible", "length": 11, "difficulty": "medium", "category": "Daily Life", "hint_th": "รับผิดชอบ", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "necessary", "length": 9, "difficulty": "medium", "category": "Daily Life", "hint_th": "จำเป็น", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "immediate", "length": 11, "difficulty": "medium", "category": "Daily Life", "hint_th": "ทันที", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "ordinary", "length": 8, "difficulty": "medium", "category": "Daily Life", "hint_th": "ธรรมดา / ทั่วไป", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "improve", "length": 7, "difficulty": "medium", "category": "Daily Life", "hint_th": "ปรับปรุง / พัฒนา", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},

        {"word": "relationship", "length": 12, "difficulty": "medium", "category": "People & Relationships", "hint_th": "ความสัมพันธ์", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "neighbor", "length": 8, "difficulty": "medium", "category": "People & Relationships", "hint_th": "เพื่อนบ้าน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "colleague", "length": 9, "difficulty": "medium", "category": "People & Relationships", "hint_th": "เพื่อนร่วมงาน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "relative", "length": 8, "difficulty": "medium", "category": "People & Relationships", "hint_th": "ญาติ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "supportive", "length": 10, "difficulty": "medium", "category": "People & Relationships", "hint_th": "ให้การสนับสนุน", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "respectful", "length": 10, "difficulty": "medium", "category": "People & Relationships", "hint_th": "ให้ความเคารพ", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "friendly", "length": 8, "difficulty": "medium", "category": "People & Relationships", "hint_th": "เป็นมิตร", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "confident", "length": 9, "difficulty": "medium", "category": "People & Relationships", "hint_th": "มั่นใจ", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "honest", "length": 6, "difficulty": "medium", "category": "People & Relationships", "hint_th": "ซื่อสัตย์", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "patient", "length": 7, "difficulty": "medium", "category": "People & Relationships", "hint_th": "อดทน", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "polite", "length": 6, "difficulty": "medium", "category": "People & Relationships", "hint_th": "สุภาพ", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "communicate", "length": 11, "difficulty": "medium", "category": "People & Relationships", "hint_th": "สื่อสาร", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "discuss", "length": 7, "difficulty": "medium", "category": "People & Relationships", "hint_th": "พูดคุย / อภิปราย", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "advice", "length": 6, "difficulty": "medium", "category": "People & Relationships", "hint_th": "คำแนะนำ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "trust", "length": 5, "difficulty": "medium", "category": "People & Relationships", "hint_th": "ความไว้วางใจ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "similar", "length": 7, "difficulty": "medium", "category": "People & Relationships", "hint_th": "คล้ายกัน", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "different", "length": 9, "difficulty": "medium", "category": "People & Relationships", "hint_th": "แตกต่าง", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "experience", "length": 10, "difficulty": "medium", "category": "People & Relationships", "hint_th": "ประสบการณ์", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "behavior", "length": 8, "difficulty": "medium", "category": "People & Relationships", "hint_th": "พฤติกรรม", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "personality", "length": 11, "difficulty": "medium", "category": "People & Relationships", "hint_th": "บุคลิกภาพ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},

        {"word": "assignment", "length": 10, "difficulty": "medium", "category": "Education", "hint_th": "งานที่ได้รับมอบหมาย", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "lecture", "length": 7, "difficulty": "medium", "category": "Education", "hint_th": "การบรรยาย", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "semester", "length": 8, "difficulty": "medium", "category": "Education", "hint_th": "ภาคการศึกษา", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "subject", "length": 7, "difficulty": "medium", "category": "Education", "hint_th": "วิชา", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "academic", "length": 8, "difficulty": "medium", "category": "Education", "hint_th": "ด้านการศึกษา", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "research", "length": 8, "difficulty": "medium", "category": "Education", "hint_th": "การวิจัย", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "knowledge", "length": 9, "difficulty": "medium", "category": "Education", "hint_th": "ความรู้", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "practice", "length": 8, "difficulty": "medium", "category": "Education", "hint_th": "การฝึกฝน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "exam", "length": 4, "difficulty": "medium", "category": "Education", "hint_th": "การสอบ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "grade", "length": 5, "difficulty": "medium", "category": "Education", "hint_th": "คะแนน / เกรด", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "project", "length": 7, "difficulty": "medium", "category": "Education", "hint_th": "โครงงาน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "presentation", "length": 12, "difficulty": "medium", "category": "Education", "hint_th": "การนำเสนอ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "deadline", "length": 8, "difficulty": "medium", "category": "Education", "hint_th": "กำหนดส่ง", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "concentrate", "length": 11, "difficulty": "medium", "category": "Education", "hint_th": "มีสมาธิ", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "memorize", "length": 8, "difficulty": "medium", "category": "Education", "hint_th": "ท่องจำ", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "understand", "length": 10, "difficulty": "medium", "category": "Education", "hint_th": "เข้าใจ", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "review", "length": 6, "difficulty": "medium", "category": "Education", "hint_th": "ทบทวน", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "explain", "length": 7, "difficulty": "medium", "category": "Education", "hint_th": "อธิบาย", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "progress", "length": 7, "difficulty": "medium", "category": "Education", "hint_th": "ความก้าวหน้า", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "skill", "length": 5, "difficulty": "medium", "category": "Education", "hint_th": "ทักษะ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},

        {"word": "career", "length": 6, "difficulty": "medium", "category": "Work & Career", "hint_th": "อาชีพ / เส้นทางอาชีพ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "employee", "length": 8, "difficulty": "medium", "category": "Work & Career", "hint_th": "พนักงาน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "employer", "length": 8, "difficulty": "medium", "category": "Work & Career", "hint_th": "นายจ้าง", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "position", "length": 8, "difficulty": "medium", "category": "Work & Career", "hint_th": "ตำแหน่งงาน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "interview", "length": 9, "difficulty": "medium", "category": "Work & Career", "hint_th": "การสัมภาษณ์", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "salary", "length": 6, "difficulty": "medium", "category": "Work & Career", "hint_th": "เงินเดือน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "workplace", "length": 10, "difficulty": "medium", "category": "Work & Career", "hint_th": "สถานที่ทำงาน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "responsibility", "length": 14, "difficulty": "medium", "category": "Work & Career", "hint_th": "ความรับผิดชอบ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "meeting", "length": 7, "difficulty": "medium", "category": "Work & Career", "hint_th": "การประชุม", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "promotion", "length": 7, "difficulty": "medium", "category": "Work & Career", "hint_th": "การเลื่อนตำแหน่ง", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "workload", "length": 8, "difficulty": "medium", "category": "Work & Career", "hint_th": "ปริมาณงาน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "professional", "length": 12, "difficulty": "medium", "category": "Work & Career", "hint_th": "เป็นมืออาชีพ", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "manager", "length": 7, "difficulty": "medium", "category": "Work & Career", "hint_th": "ผู้จัดการ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "department", "length": 10, "difficulty": "medium", "category": "Work & Career", "hint_th": "แผนก", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "shift", "length": 8, "difficulty": "medium", "category": "Work & Career", "hint_th": "กะการทำงาน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "training", "length": 8, "difficulty": "medium", "category": "Work & Career", "hint_th": "การฝึกอบรม", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "task", "length": 4, "difficulty": "medium", "category": "Work & Career", "hint_th": "งาน / หน้าที่", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "occupation", "length": 6, "difficulty": "medium", "category": "Work & Career", "hint_th": "อาชีพ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "promote", "length": 7, "difficulty": "medium", "category": "Work & Career", "hint_th": "เลื่อนตำแหน่ง", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "achieve", "length": 7, "difficulty": "medium", "category": "Work & Career", "hint_th": "บรรลุ / ทำสำเร็จ", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},

        {"word": "ingredient", "length": 9, "difficulty": "medium", "category": "Food & Dining", "hint_th": "ส่วนผสม", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "restaurant", "length": 10, "difficulty": "medium", "category": "Food & Dining", "hint_th": "ร้านอาหาร", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "menu", "length": 4, "difficulty": "medium", "category": "Food & Dining", "hint_th": "เมนูอาหาร", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "order", "length": 5, "difficulty": "medium", "category": "Food & Dining", "hint_th": "สั่งอาหาร", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "delicious", "length": 9, "difficulty": "medium", "category": "Food & Dining", "hint_th": "อร่อย", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "flavor", "length": 6, "difficulty": "medium", "category": "Food & Dining", "hint_th": "รสชาติ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "portion", "length": 7, "difficulty": "medium", "category": "Food & Dining", "hint_th": "ปริมาณ / ส่วน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "healthy", "length": 7, "difficulty": "medium", "category": "Food & Dining", "hint_th": "มีสุขภาพดี", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "vegetable", "length": 9, "difficulty": "medium", "category": "Food & Dining", "hint_th": "ผัก", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "beverage", "length": 8, "difficulty": "medium", "category": "Food & Dining", "hint_th": "เครื่องดื่ม", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "dessert", "length": 7, "difficulty": "medium", "category": "Food & Dining", "hint_th": "ของหวาน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "recommend", "length": 9, "difficulty": "medium", "category": "Food & Dining", "hint_th": "แนะนำ", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "taste", "length": 5, "difficulty": "medium", "category": "Food & Dining", "hint_th": "รสชาติ / ลิ้มรส", "part_of_speech": "N. / V.", "times_used": 0, "is_picked": "no"},
        {"word": "fresh", "length": 5, "difficulty": "medium", "category": "Food & Dining", "hint_th": "สดใหม่", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "spicy", "length": 5, "difficulty": "medium", "category": "Food & Dining", "hint_th": "เผ็ด", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "sweet", "length": 5, "difficulty": "medium", "category": "Food & Dining", "hint_th": "หวาน", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "bitter", "length": 6, "difficulty": "medium", "category": "Food & Dining", "hint_th": "ขม", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "receipt", "length": 7, "difficulty": "medium", "category": "Food & Dining", "hint_th": "ใบเสร็จ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "cuisine", "length": 7, "difficulty": "medium", "category": "Food & Dining", "hint_th": "อาหาร / รูปแบบอาหาร", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "diet", "length": 4, "difficulty": "medium", "category": "Food & Dining", "hint_th": "การควบคุมอาหาร", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},

        {"word": "journey", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "การเดินทาง", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "destination", "length": 11, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "จุดหมายปลายทาง", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "transportation", "length": 14, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "การขนส่ง / การเดินทาง", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "departure", "length": 9, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "การออกเดินทาง", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "arrival", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "การมาถึง", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "ticket", "length": 6, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "ตั๋ว", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "station", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "สถานี", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "traffic", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "การจราจร", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "vehicle", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "ยานพาหนะ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "direction", "length": 9, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "ทิศทาง", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "route", "length": 5, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "เส้นทาง", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "luggage", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "สัมภาระ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "passport", "length": 8, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "หนังสือเดินทาง", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "booking", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "การจอง", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "hotel", "length": 5, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "โรงแรม", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "explore", "length": 7, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "สำรวจ", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "local", "length": 5, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "ท้องถิ่น", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "foreign", "length": 6, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "ต่างประเทศ", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "delay", "length": 5, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "ความล่าช้า", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "comfortable", "length": 10, "difficulty": "medium", "category": "Travel & Transportation", "hint_th": "สะดวกสบาย", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},

        {"word": "exercise", "length": 8, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "การออกกำลังกาย", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "active", "length": 7, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "กระฉับกระเฉง", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "lifestyle", "length": 9, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "รูปแบบการใช้ชีวิต", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "nutrition", "length": 9, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "โภชนาการ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "habit", "length": 5, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "นิสัย / กิจวัตร", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "sleep", "length": 5, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "การนอนหลับ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "stress", "length": 6, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ความเครียด", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "relax", "length": 5, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ผ่อนคลาย", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "energy", "length": 6, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "พลังงาน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "balance", "length": 7, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "สมดุล", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "prevent", "length": 7, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ป้องกัน", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "recover", "length": 7, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ฟื้นตัว", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "condition", "length": 9, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "สภาพ / ภาวะ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "regular", "length": 7, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "สม่ำเสมอ", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "physical", "length": 8, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ทางกายภาพ", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "mental", "length": 6, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ทางจิตใจ", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "medical", "length": 7, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ทางการแพทย์", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "symptom", "length": 7, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "อาการ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "treatment", "length": 9, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "การรักษา", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "immunity", "length": 8, "difficulty": "medium", "category": "Health & Lifestyle", "hint_th": "ภูมิคุ้มกัน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},

        {"word": "technology", "length": 10, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "เทคโนโลยี", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "device", "length": 6, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "อุปกรณ์", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "application", "length": 11, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "แอปพลิเคชัน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "software", "length": 8, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ซอฟต์แวร์", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "hardware", "length": 8, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ฮาร์ดแวร์", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "network", "length": 7, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "เครือข่าย", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "account", "length": 7, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "บัญชีผู้ใช้", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "password", "length": 8, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "รหัสผ่าน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "privacy", "length": 7, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ความเป็นส่วนตัว", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "connection", "length": 8, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "การเชื่อมต่อ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "message", "length": 7, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ข้อความ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "communication", "length": 13, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "การสื่อสาร", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "download", "length": 8, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ดาวน์โหลด", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "upload", "length": 6, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "อัปโหลด", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "connect", "length": 7, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "เชื่อมต่อ", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "digital", "length": 7, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ดิจิทัล", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "online", "length": 6, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ออนไลน์", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "update", "length": 6, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "อัปเดต", "part_of_speech": "N. / V.", "times_used": 0, "is_picked": "no"},
        {"word": "search", "length": 6, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "ค้นหา", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "website", "length": 7, "difficulty": "medium", "category": "Technology & Communication", "hint_th": "เว็บไซต์", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},

        {"word": "purchase", "length": 8, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "การซื้อ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "customer", "length": 8, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ลูกค้า", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "price", "length": 5, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ราคา", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "discount", "length": 8, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ส่วนลด", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "budget", "length": 6, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "งบประมาณ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "payment", "length": 7, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "การชำระเงิน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "cash", "length": 4, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "เงินสด", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "voucher", "length": 7, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "บัตรกำนัล", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "expensive", "length": 9, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ราคาแพง", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "affordable", "length": 10, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ราคาไม่แพง", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "cheap", "length": 9, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ราคาถูก", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "save", "length": 4, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ประหยัด / ออม", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "spend", "length": 5, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ใช้จ่าย", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "income", "length": 6, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "รายได้", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "expense", "length": 7, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ค่าใช้จ่าย", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "wallet", "length": 6, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "กระเป๋าสตางค์", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "change", "length": 6, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "เงินทอน / เปลี่ยน", "part_of_speech": "N. / V.", "times_used": 0, "is_picked": "no"},
        {"word": "quality", "length": 7, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "คุณภาพ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "brand", "length": 5, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "ยี่ห้อ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "refund", "length": 6, "difficulty": "medium", "category": "Shopping & Money", "hint_th": "การคืนเงิน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},

        {"word": "environment", "length": 11, "difficulty": "medium", "category": "Environment & Society", "hint_th": "สิ่งแวดล้อม", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "pollution", "length": 9, "difficulty": "medium", "category": "Environment & Society", "hint_th": "มลพิษ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "recycle", "length": 7, "difficulty": "medium", "category": "Environment & Society", "hint_th": "รีไซเคิล", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "waste", "length": 5, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ขยะ / ของเสีย", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "community", "length": 9, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ชุมชน", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "society", "length": 7, "difficulty": "medium", "category": "Environment & Society", "hint_th": "สังคม", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "public", "length": 6, "difficulty": "medium", "category": "Environment & Society", "hint_th": "สาธารณะ", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "resource", "length": 8, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ทรัพยากร", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "conservation", "length": 6, "difficulty": "medium", "category": "Environment & Society", "hint_th": "การอนุรักษ์", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "climate", "length": 7, "difficulty": "medium", "category": "Environment & Society", "hint_th": "สภาพภูมิอากาศ", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "natural", "length": 7, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ตามธรรมชาติ", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "protect", "length": 7, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ปกป้อง", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "reduce", "length": 6, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ลด", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "increase", "length": 8, "difficulty": "medium", "category": "Environment & Society", "hint_th": "เพิ่มขึ้น", "part_of_speech": "V.", "times_used": 0, "is_picked": "no"},
        {"word": "citizen", "length": 9, "difficulty": "medium", "category": "Environment & Society", "hint_th": "พลเมือง", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "volunteer", "length": 9, "difficulty": "medium", "category": "Environment & Society", "hint_th": "อาสาสมัคร", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "awareness", "length": 14, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ความตระหนัก", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"},
        {"word": "social", "length": 6, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ทางสังคม", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "global", "length": 5, "difficulty": "medium", "category": "Environment & Society", "hint_th": "ทั่วโลก", "part_of_speech": "Adj.", "times_used": 0, "is_picked": "no"},
        {"word": "future", "length": 6, "difficulty": "medium", "category": "Environment & Society", "hint_th": "อนาคต", "part_of_speech": "N.", "times_used": 0, "is_picked": "no"}
    ]

    manager = VocabularyManager(sample_data)
    medium_items = manager.filter_by_difficulty("medium")

    categories = []
    category_names = [
        "Daily Life (ชีวิตประจำวัน)",
        "People & Relationships (ผู้คนและความสัมพันธ์)",
        "Education (การศึกษา)",
        "Work & Career (งานและอาชีพ)",
        "Food & Dining (อาหารและการรับประทานอาหาร)",
        "Travel & Transportation (การเดินทางและพาหนะ)",
        "Health & Lifestyle (สุขภาพและการใช้ชีวิต)",
        "Technology & Communication (เทคโนโลยีและการสื่อสาร)",
        "Shopping & Money (การซื้อของและการเงิน)",
        "Environment & Society (สิ่งแวดล้อมและสังคม)"
    ]

    for category_name in category_names:
        category_words = []

        for item in medium_items:
            if item.get("category") == category_name.split(" (")[0]:
                category_words.append(
                    f"{item.get('word')} = {item.get('hint_th')} ({item.get('part_of_speech')})"
                )

        categories.append({
            "name": category_name,
            "words": category_words
        })

    return {
        "description": "หมวดคำศัพท์ทั้งหมด",
        "categories": categories
    } 
